site_name: MkDocs
site_url: https://www.mkdocs.org/
site_description: Project documentation with Markdown.
site_author: MkDocs Team

repo_url: https://github.com/mkdocs/mkdocs/
edit_uri: ""

theme:
    # name: mkdocs
    name: material
    locale: en
    # analytics: {gtag: 'G-274394082'}
    # highlightjs: true
    # hljs_languages:
    #     - yaml
    #     - django

nav:
    - Home: index.md
    - Getting Started: getting-started.md
    - Bloc de Code:
            - fc-blocs-code-mkdocs.md
            - fc-blocs-code-oscp.md
    # - getting-started.md # title from h1 of page
    - User Guide:
        - Overview: user-guide/index.md
        - Installation: user-guide/installation.md
        - Writing Your Docs: user-guide/writing-your-docs.md
        - Choosing Your Theme: user-guide/choosing-your-theme.md
        - Customizing Your Theme: user-guide/customizing-your-theme.md
        - Localizing Your Theme: user-guide/localizing-your-theme.md
        - Configuration: user-guide/configuration.md
        - Deploying Your Docs: user-guide/deploying-your-docs.md
    # - Developer Guide:
    #     - Overview: dev-guide/index.md
    #     # - Themes: 
    #     - dev-guide/themes.md
    #     - Translations: dev-guide/translations.md
    #    - Plugins: dev-guide/plugins.md
    # - About:
    #     - Release Notes: about/release-notes.md
    #     - Contributing: about/contributing.md
    #     - License: about/license.md

extra_css:
    - css/extra.css

markdown_extensions:
    # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/
    - pymdownx.highlight:
    #    anchor_linenums: true
    # - pymdownx.inlinehilite
    # - pymdownx.snippets
    - pymdownx.superfences

    # fc must be installed
    # https://pypi.org/project/markdown-captions/
    - markdown_captions # must be installed https://pypi.org/project/markdown-captions/
    
    # - md_in_html # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/
    - toc:
#        permalink: "#"
    - admonition
    - attr_list
    - def_list
#    - mdx_gh_links:
#        user: mkdocs
#        repo: mkdocs

copyright: Copyright &copy; 2014 <a href="https://twitter.com/_tomchristie">Tom Christie</a>, Maintained by the <a href="/about/release-notes/#maintenance-team">MkDocs Team</a>.

# use_directory_urls: false

plugins:
    - search
    # fc export plugin
    - md2wpmr:
        # matrix
        number_column : 50
        number_row_toc : 5200
        number_row_pages : 5400
        # toc
        toc_page_level_depth: 2


#    - redirects:
#        redirect_maps:
#            user-guide/plugins.md: dev-guide/plugins.md
#            user-guide/custom-themes.md: dev-guide/themes.md
#            user-guide/styling-your-docs.md: user-guide/choosing-your-theme.md
